server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    name: seckill
    url: jdbc:mysql://127.0.0.1:3306/seckill
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: 192.168.153.131
    database: 10
    password:
    jedis:
      pool:
        #设置jedis连接池，设置最大连接数以及最小idle
        max-active: 50
        min-idle: 20
  rabbitmq:
    host: 192.168.153.131
    port: 5672
    username: guest
    password: guest
    virtualHost: /



